# Generated by Django 2.1 on 2018-08-09 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ep04', '0002_post_autohr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='autohr',
            new_name='author',
        ),
    ]
